'use client'
import Head from 'next/head'
import { SaveClient } from '@/components/ui/custom/clientes/save-client'
import { ClientDataTable } from '@/components/ui/custom/clientes/client-data-table'

export default function Cadastros() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-start items-center p-6 md:p-12 lg:p-24 pt-2 md:pt-4 lg:pt-8 min-h-screen'>
        <div className="w-full mt-2">
          <SaveClient/>
          <ClientDataTable />
        </div>
      </main>
    </>
  )
}
