'use client'
import Head from 'next/head'
import { SaveClient } from '@/components/ui/custom/clientes/save-client'
import { ClientDataTable } from '@/components/ui/custom/clientes/client-data-table'
import { AuthProvider } from '@/components/ui/custom/auth-provider'

export default function Cadastros() {

  return (
    <AuthProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-start items-center p-6 md:p-12 lg:p-24 py-2 md:py-4 lg:py-8 min-h-screen gap-2'>
        <div className="w-full mt-2">
          <SaveClient/>
          <ClientDataTable />
        </div>
      </main>
    </AuthProvider>
  )
}
