'use client'
import Head from 'next/head'
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import EntranceDataTable from '@/components/ui/custom/transacoes/entrances/entrance-data-table'
import ExitDataTable from '@/components/ui/custom/transacoes/exits/exit-data-table'

export default function FinancialTransactions() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-start items-center p-6 md:p-12 lg:p-24 pt-2 md:pt-4 lg:pt-8 min-h-screen'>
        <Tabs defaultValue="entrances" className="w-full mt-2">
          <TabsList>
            <TabsTrigger value="entrances">Entradas</TabsTrigger>
            <TabsTrigger value="exits">Saídas</TabsTrigger>
          </TabsList>
          <TabsContent value="entrances">
            <EntranceDataTable />
          </TabsContent>
          <TabsContent value="exits">
            <ExitDataTable />
          </TabsContent>
        </Tabs>
      </main>
    </>
  )
}
