'use client'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Handshake, PiggyBank, Banknote, Gem, CreditCard, Percent } from 'lucide-react';
import HeadInfoCard from '@/components/ui/custom/contratos/head-info-card';
import { ContractDataTable } from '@/components/ui/custom/contratos/contract-data-table';
import { AuthProvider } from '@/components/ui/custom/auth-provider';

const inter = Inter({ subsets: ['latin'] });

export default function Contracts() {

  return (
    <AuthProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-start items-center p-6 md:p-12 lg:p-24 py-2 md:py-4 lg:py-8 min-h-screen gap-2'>
        <div className='w-full flex justify-between items-center my-4 gap-4 md:gap-2 flex-wrap'>
          <HeadInfoCard
            title='Total Investido'
            value='10'
            description='+20.1% from last month'
            Icon={Banknote}
          />
          <HeadInfoCard
            title='Rec. Principal'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Handshake}
          />
          <HeadInfoCard
            title='Rec. Juros'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Percent}
          />
          <HeadInfoCard
            title='Prov. Juros'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Gem}
          />
          <HeadInfoCard
            title='Atrasado'
            value='10000.00'
            description='+20.1% from last month'
            Icon={CreditCard}
          />
          <HeadInfoCard
            title='Total a Receber'
            value='10000.00'
            description='+20.1% from last month'
            Icon={PiggyBank}
          />
        </div>

        <ContractDataTable />
      </main>
    </AuthProvider>
  )
}
