'use client'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import HeadInfoCard from './components/head-info-card'
import { LoanDataTable } from './components/loan-data-table'
import { Handshake, PiggyBank, Banknote, Gem, CreditCard, Percent } from 'lucide-react';

const inter = Inter({ subsets: ['latin'] });

export default function Contracts() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-start items-center p-6 md:p-12 lg:p-24 pt-2 md:pt-4 lg:pt-8 min-h-screen'>
        <div className='w-full flex justify-between items-center my-4 gap-4 md:gap-2 flex-wrap'>
          <HeadInfoCard
            title='Total Investido'
            value='10'
            description='+20.1% from last month'
            Icon={Banknote}
          />
          <HeadInfoCard
            title='Rec. Principal'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Handshake}
          />
          <HeadInfoCard
            title='Rec. Juros'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Percent}
          />
          <HeadInfoCard
            title='Prov. Juros'
            value='10000.00'
            description='+20.1% from last month'
            Icon={Gem}
          />
          <HeadInfoCard
            title='Atrasado'
            value='10000.00'
            description='+20.1% from last month'
            Icon={CreditCard}
          />
          <HeadInfoCard
            title='Total a Receber'
            value='10000.00'
            description='+20.1% from last month'
            Icon={PiggyBank}
          />
        </div>

        <LoanDataTable />
      </main>
    </>
  )
}
